# Site settings
title: Ancient History Blog
description: The Macquarie University Ancient History Blog contains News, Events, Announcements, and Updates from the Field.
cover: assets/images/dawn.png
logo: assets/images/MQ_INT_HOR_RGB_POS.png
favicon: assets/images/favicon/apple-touch-icon-180x180-precomposed.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://mqancienthistory.github.io" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: https://mq.edu.au/privacy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


  


# Settings for rake task
safe: False
lsi: False
username: samanyougarg #github username
repo: hanuman #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - "*.sh"
  - "*.bak"